In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    # a layer without any param
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net=nn.Sequential(nn.Linear(8,128),CenteredLayer())

In [4]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(1.2573e-08, grad_fn=<MeanBackward0>)

In [8]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(
            torch.randn(
                units,
            )
        )

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [9]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.7789,  0.1541,  1.2047],
        [ 0.8795, -1.0816, -1.1743],
        [-1.0327, -0.5776, -1.5629],
        [ 1.5798, -0.2355, -0.5068],
        [-1.6108,  0.8492,  0.1876]], requires_grad=True)

In [11]:
linear(torch.rand(2, 5))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])