In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True)  # same as x=torch.arange(4.0,requires_grad=True)
x.grad

In [3]:
# y=2x^Tx
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
y.backward()  # backpropagate the gradients of x
# The gradient of y is 4x
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
x.grad == 4 * x

tensor([True, True, True, True])

In [6]:
# Pytorch tends to accumulate the gradients
# clear the values to zero
x.grad.zero_()
# y=sum(x)
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [12]:
x.grad.zero_()
y = x * x
print(y)
y.sum().backward()
x.grad

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)


tensor([0., 2., 4., 6.])

In [13]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
# u has no information of y but has the same value as y (aka u is detached from y)
# that is to say, when calculating the gradient of Zx, u is seen as a constant
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [14]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [15]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [18]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [19]:
a.grad == d / a

tensor(True)